[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[dependencies]
protobuf = "1.*"
futures = "0.1"
grpcio = "0.1"

[replace."grpcio:0.1.2"]
path = "/home/qupeng/github.com/pingcap/grpc-rs"
